name: Build Production
'on':
  push:
    branches:
      - develop
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Grand execute permissions to gradlew
        run: chmod +x gradlew
      - name: Restore keystore.jks
        run: |
          echo ${{secrets.KEYSTORE}} > keystore_base64.txt
          mkdir ${{secrets.KEYSTORE_DIR}}
          base64 -d  keystore_base64.txt > "${{ secrets.KEYSTORE_DIR }}/${{ secrets.KEYSTORE_FILE_NAME }}"

      - name: Generate keystore.properties
        run: |
          cat <<EOF > keystore.properties
          storePassword:${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword:${{ secrets.ALIAS_PASSWORD }}
          keyAlias:${{ secrets.ALIAS_NAME }}
          storeFile:'..${{ secrets.KEYSTORE_DIR }}/${{ secrets.KEYSTORE_FILE_NAME }}'
          EOF

      - name: Lint
        run: ./gradlew lintDebug

      - name: Test
        run: ./gradlew testDebug

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
  build:
    name: Build Signed AAB
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Setup Gradle Cache
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{github.run_number}}
          versionName: 1.0.0

      - name: Build prodRelease
        run: ./gradlew assembleRelease

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.ALIAS_NAME }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ALIAS_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      - name: Upload apk release as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: app/build/outputs/apk/release/app-release.apk
      - run: 'echo Build status report=${{ job.status }}'
      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: Test-Reports
          path: app/build/reports
        if: ${{ always() }}