name: Build Production
'on':
  push:
    branches:
      - develop
jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Grand execute permissions to gradlew
        run: chmod +x gradlew
      - name: Run Linters and Test
        run: ./gradlew check
  build:
    name: Build Signed AAB
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Setup Gradle Cache
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.2
        with:
          gradlePath: app/build.gradle.kts
          versionCode: '${{github.run_number}}'
          versionName: 1.0.0
      - name: Build prodRelease
        run: ./gradlew bundleRelease
      - name: Sign AAb
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: '${{ secrets.KEYSTORE }}'
          alias: '${{ secrets.APP_NAME_KEY }}'
          keyStorePassword: '${{ secrets.KEYSTORE_PASSWORD }}'
          keyPassword: '${{ secrets.APP_NAME_KEY_PASSWORD }}'
      - name: Upload app bundle as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-bundle
          path: app/build/outputs/bundle/release/app-release.aab
      - run: 'echo Build status report=${{ job.status }}'