name: Build Production
'on':
  push:
    branches:
      - develop
jobs:

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grand execute permissions to gradlew
        run: chmod +x gradlew

      - name: Run Ktlint
        run: ./gradlew ktlintDebugSourceSetCheck ktlintTestDebugSourceSetCheck

      - name: Test
        run: ./gradlew testDebug

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless

  build:
    name: Build Signed APK
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4.1.7

      - name: Set Up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Gradle Cache
        uses: gradle/gradle-build-action@v3.4.2
        with:
          gradle-home-cache-cleanup: true

      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{github.run_number}}
          versionName: 1.0.0

      - name: Build prodRelease
        run: ./gradlew assembleRelease

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.ALIAS_NAME }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ALIAS_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload apk release as artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: app-apk
          path: app/build/outputs/apk/release/app-release.apk
      - run: 'echo Build status report=${{ job.status }}'
      - name: Upload Reports
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Test-Reports
          path: app/build/reports
        if: ${{ always() }}