name: Build Production
'on':
  push:
    branches:
      - develop
jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Grand execute permissions to gradlew
        run: chmod +x gradlew
      - name: Restore keystore.jks
        run: |
          echo ${{secrets.KEYSTORE}} > keystore_base64.txt
          mkdir ${{secrets.KEYSTORE_DIR}}
          base64 -d  keystore_base64.txt > "${{ secrets.KEYSTORE_DIR }}/${{ secrets.KEYSTORE_FILE_NAME }}"

      - name: Generate keystore.properties
        run: |
          cat <<EOF > keystore.properties
          storePassword:${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword:${{ secrets.ALIAS_PASSWORD }}
          keyAlias:${{ secrets.ALIAS_NAME }}
          storeFile:"..${{ secrets.KEYSTORE_DIR }}/${{ secrets.KEYSTORE_FILE_NAME }}"
          EOF

      - name: Lint
        run: ./gradlew lintDebug
      # Execute unit tests
      - name: Unit Test
        run: ./gradlew testDebugUnitTest
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
  build:
    name: Build Signed AAB
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Setup Gradle Cache
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.2
        with:
          gradlePath: app/build.gradle.kts
          versionCode: '${{github.run_number}}'
          versionName: 1.0.0

      - name: Restore keystore.jks
        run: |
          echo ${{secrets.KEYSTORE}} > keystore_base64.txt
          mkdir ${{secrets.KEYSTORE_DIR}}
          base64 -d  keystore_base64.txt > "${{ secrets.KEYSTORE_DIR }}/${{ secrets.KEYSTORE_FILE_NAME }}"

      - name: Generate keystore.properties
        run: |
          cat <<EOF > keystore.properties
          storePassword:${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword:${{ secrets.ALIAS_PASSWORD }}
          keyAlias:${{ secrets.ALIAS_NAME }}
          storeFile:"..${{ secrets.KEYSTORE_DIR }}/${{ secrets.KEYSTORE_FILE_NAME }}"
          EOF

      - name: Build prodRelease
        run: ./gradlew assembleRelease

      - name: Upload app bundle as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-bundle
          path: app/build/outputs/bundle/release/app-release.aab
      - run: 'echo Build status report=${{ job.status }}'
      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: Test-Reports
          path: app/build/reports
        if: ${{ always() }}