name: Run Unit Test on demand
'on':
  workflow_dispatch: null
  pull_request:
    branches: [main, develop]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Grand execute permissions to gradlew
        run: chmod +x gradlew

      - name: Lint
        run: ./gradlew lintDebug

      - name: Unit Test
        run: ./gradlew testDebug

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
